### ISSUE TITLE
The cipher and / or key length are invalid

### ISSUE THREAD

**Issue by Ovski4** [etopian/docker-koel#4]
When I ran the docker image, I got an error

```
Whoops, looks like something went wrong.
```

Here are more details. I checked the logs:

```
docker exec -it my_koel_container bash
tail -f /DATA/htdocs/storage/logs/laravel.log
```

Which gave me:

```
[2015-12-20 11:56:14] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /DATA/htdocs/bootstrap/cache/compiled.php:7020
Stack trace:
#0 /DATA/htdocs/bootstrap/cache/compiled.php(1284): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(App\Application), Array)
#1 /DATA/htdocs/bootstrap/cache/compiled.php(1237): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /DATA/htdocs/bootstrap/cache/compiled.php(1775): Illuminate\Container\Container->make('encrypter', Array)
#3 /DATA/htdocs/bootstrap/cache/compiled.php(1329): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 /DATA/htdocs/bootstrap/cache/compiled.php(1313): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /DATA/htdocs/bootstrap/cache/compiled.php(1299): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /DATA/htdocs/bootstrap/cache/compiled.php(1237): Illuminate\Container\Container->build('App\\Http\\Middle...', Array)
#7 /DATA/htdocs/bootstrap/cache/compiled.php(1775): Illuminate\Container\Container->make('App\\Http\\Middle...', Array)
#8 /DATA/htdocs/bootstrap/cache/compiled.php(9577): Illuminate\Foundation\Application->make('App\\Http\\Middle...')
#9 /DATA/htdocs/bootstrap/cache/compiled.php(2983): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /DATA/htdocs/bootstrap/cache/compiled.php(9577): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /DATA/htdocs/bootstrap/cache/compiled.php(9567): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /DATA/htdocs/bootstrap/cache/compiled.php(2249): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /DATA/htdocs/bootstrap/cache/compiled.php(2232): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /DATA/htdocs/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
```

I fixed this error by running the following command

```
php /DATA/htdocs/artisan key:generate
```

I'm not familiar with laravel. Maybe you know how to fix it permanently ?

**Comment by Ovski4** [comment]
I think it might be related to the 70th line in the Dockerfile

```
#RUN su nginx -c "cd /DATA/htdocs && php artisan init"
```

Why did you comment that line?

**Comment by etopian** [comment]
read the instructions more carefully. the last line is commented out because the image needs to initialize as a container with various variables before you can run that command.

**Comment by Ovski4** [comment]
I missed that! Thanks :)
